postgres:
    image: postgres:15-alpine
    container_name: "${PROJECT_NAME}-${NAMESPACE}-postgres"
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
    volumes:
      - ${PROJECT_NAME}-${NAMESPACE}-postgres-data:/var/lib/postgresql/data
      - ./scripts/postgres:/docker-entrypoint-initdb.d

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - ${PG_PORT}:5432
    env_file: .env
