version: "3"
services:
  ${PROJECT_NAME}:
    image: ${DOCKER_REGISTRY}/${PROJECT_NAME}/${NAMESPACE}:${DOCKER_TAG_VERSION}
    container_name: "$PROJECT_NAME"
    environment:
    restart: unless-stopped
    depends_on:
    env_file: .env
